NAME_MAX_LENGTH = 124
SURNAME_MAX_LENGTH = 124
PHONE_MAX_LENGTH = 12
ABOUT_MAX_LENGTH = 256
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"

AVATAR_SIZE = 200
AVATAR_FONT_SIZE = 100

COLOR_BLUE = "#5B8CFF"
COLOR_RED = "#FF7B7B"
COLOR_GREEN = "#6BCB77"
COLOR_YELLOW = "#FFD166"
COLOR_PURPLE = "#A78BFA"
COLOR_ORANGE = "#F97316"
COLOR_CYAN = "#06B6D4"
COLOR_PINK = "#EC4899"
COLOR_LIME = "#84CC16"
COLOR_LIGHT_ORANGE = "#FB923C"

PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12
SKILLS_AUTOCOMPLETE_LIMIT = 10
SKILL_NAME_MAX_LENGTH = 124

AVATAR_COLORS = [
    COLOR_BLUE,
    COLOR_RED,
    COLOR_GREEN,
    COLOR_YELLOW,
    COLOR_PURPLE,
    COLOR_ORANGE,
    COLOR_CYAN,
    COLOR_PINK,
    COLOR_LIME,
    COLOR_LIGHT_ORANGE,
]
